export const EDIT_TEAM = "EDIT_TEAM";
export const EDIT_GW_INFO = "EDIT_GW_INFO";
export const ADD_HERO_DETAILS = "ADD_HERO_DETAILS";
export const ADD_ARTIFACT_DETAILS = "ADD_ARTIFACT_DETAILS";
export const LOAD_HERO_MAP = "LOAD_HERO_MAP";
export const LOAD_ARTIFACT_MAP = "LOAD_ARTIFACT_MAP";
export const INIT_GAPI = "INIT_GAPI";
